distributable:
  url: https://github.com/zyedidia/micro/archive/refs/tags/v{{version.raw}}.tar.gz
  strip-components: 1

versions:
  github: zyedidia/micro
  strip: /v /

build:
  script: |
    make build
    mkdir -p "{{ prefix }}"/bin
    mv micro "{{ prefix }}"/bin
  dependencies:
    go.dev: ^1.18

test:
  micro --version

provides:
  - bin/micro
